mixed layer documentation
ExeClim/Isca pull request #188
Opened 2020-09-24 08:15 UTC by matthewjhenry

2020-09-24 08:40 UTC, penmaher commented
Hi Matthew. Thanks for getting this done. I am happy to review this but the earliest I can start is the end of next week. Sorry for the delay.

2020-10-21 10:00 UTC, penmaher requested changes
Hi Mat, This is looking great. I have done my first read though which was to make sure nothing was missing and things make sense. Which on a whole they do :-) Lay look great and is logical for this doc. I plan to do a second read through to check the science bits. I will do that this afternoon and add any relevant comments on the PR front page. Penny

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +The mixed layer code is located in: src/atmos_spectral/driver/solo/mixed_layer.F90. The name of this file reflects the fact that the code determines the properties of the single layer (either a slab
The file locations here (4 total) don't jump out at me. Suggest using ``link`` notation to make them red.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Relevant routines which (which have not already been listed in SST options above) are called by the mixed layer ocean are:
I don't think this clause is needed. Easier to read without it. If you like bullet points here I suggest using the same for the .F90 files above too.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +| t_surf            | Surface temperature                 | :math:`\text{K}\`                  |
t_surf and delta_t_surf have not rendered properly. I can't see any bug here but perhaps it is the last '\'.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +| ice_conc          | Sea ice concentration               | None                               |
Perhaps rather than saying none in these two, say Unitless with a range of 0-1 or similar?

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +
Can you add land_sea_heat_capacity please?

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +| Option               | Summary                                                                                                                                                                    |De
Why are these as 2 tables? I think line wrapping would look better than a scrolling bar. What is your perspective?

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Other options (temporary title)
Title update needed.You missed the following options:
trop_depth, trop_cap_limit, heat_cap_limit, np_cap_factor, flux_lhe_anom_file_name, flux_lhe_anom_field_name

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +    - a slab ocean aquaplanet analytic form (``prescribe_initial_dist`` namelist option)
Can you add a reference here please? I assume one of Frierson's papers but check the form in the paper to make sure.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +    - a slab ocean aquaplanet analytic form (``prescribe_initial_dist`` namelist option)
Sorry don't put the ref here but in the section below.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Set ``do_sc_sst`` to True if you want to specify the SST field. The SST field will be read in from an input filename using the ``sst_file`` variable.
mentioned somewhere in here the file needs to be NetCDF

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +:math:`T_s = T_{surf} -\frac{1}{3}*dT*\left(3\sin(\lambda)^2-1\right)`,
the * looks strange here. Suggest removing.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +where the default values we use in the trip test for the Frierson test case (exp/test_cases/frierson/frierson_test_case.py) are: :math:`T_{surf} = 285 K` and :math:`dT = 40 K`.
use `` link`` notation to make it red

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Implicit timestep
Add you add a general english sentence her eon what implicit time stepping is please.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +are then used to compute the Q-flux by running the offline python script: src/extra/python/scripts/calculate_qflux/calculate_qflux.py. This script produces a .nc file which is then passed into the mo
``link`` notation please

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +If ``do_qflux`` is True, use ``qflux_amp`` and ``qflux_width`` to calculate a time-independent surface q-flux.
Could you add a sentence above in the q-flux description to include how the qflux_amp and qflux_width work?

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Additional Q-flux
Perhaps 'Optional' rather than 'Additional'?

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +If ``do_qflux`` is True, use ``qflux_amp`` and ``qflux_width`` to calculate a time-independent surface q-flux.
Okay I get why there are two tables now. Could you separate the text above into two sections corresponding to each table please? Might make it more obvious.

2020-10-21 10:00 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +There are X options for setting up the land, determined by the value of ``land_option``.
X=4?

2020-10-22 08:08 UTC, penmaher commented
Science things to check. Line ref are for mixed_layer.F90

- L339:  The T_s and T_surf notation in documentation is a little confusing. Suggest using T_C or another form (unless it is stated T_surf in a paper somewhere in which case it if probably fine).

- In the surface albedo options section, the notation in 1-5 if hard to read/follow. There are some notation errors here too (eg the end of item 4). Could you work on making this easier to understand please?

-  The implicit time stepping equation (land_sea_heat_capacity * dTs/dt = - corrected_flux - t_surf_dependence * dTs) I can't find it in this form in the code.  L721 is similar. Can you check this form please? In general I found this section on time stepping a little hard to follow (notation is a primary reason why I found it hard to follow - maybe a different appearance for the variable names might help readability?)
- description in table for tconst and delta_T mention a formulas above, suggest you say in what section

- the albedo section has 2 sets of variables with the same description. Can you make it clearer how they are different?

- in the 'others' section. Perhaps a 'sea ice' section might help. Also do_ape_sst, sst_file and some others here  would work in the section "Initialize surface temperature". Perhaps anything else that does not fit could be described  as 'Optional extras'?

Okay that is all I see for now. Over to you @matthewjhenry

2020-12-09 13:18 UTC, matthewjhenry commented
Hi Penny, 

Thanks for all the comments. Here are a few responses.

I know they are in the code, but are the "trop_depth, trop_cap_limit, heat_cap_limit, np_cap_factor, flux_lhe_anom_file_name, flux_lhe_anom_field_name" options still used? Somehow I remember reading they weren't hence weren't added to the doc, but maybe I am wrong on this.

>     * L339:  The T_s and T_surf notation in documentation is a little confusing. Suggest using T_C or another form (unless it is stated T_surf in a paper somewhere in which case it if probably fine).

L339 refers to mixed_layer.F90 code? Confused.

>     * The implicit time stepping equation (land_sea_heat_capacity * dTs/dt = - corrected_flux - t_surf_dependence * dTs) I can't find it in this form in the code.  L721 is similar. Can you check this form please? 

It's not used, the expression under it is used : eff_heat_capacity * dTs/dt = - corrected_flux (L. 713 in mixed_layer.F90). I don't think adding mixed_layer.F90 line numbers makes sense, as it may change a lot in the future.

>     * the albedo section has 2 sets of variables with the same description. Can you make it clearer how they are different?

I think it's maybe clearer now. It just depends on what albedo_choice one chooses.

Let me know if you have any other comments, also don't hesitate to upload changes directly.

-Matthew

2021-01-14 11:12 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Other options (temporary title)
Did you decide not to include these options or was this missed?

2021-01-14 11:15 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +:math:`T_s = T_{surf} -\frac{1}{3}*dT*\left(3\sin(\lambda)^2-1\right)`,
The math in this section "APE aquaplanet (analytic form)" is not rendering correctly

2021-01-14 11:22 UTC, penmaher commented on docs/source/modules/mixedlayer.rst
> +Other options (temporary title)
Sorry only now saw your response from 9 Dec. No problem to not include them.

2021-01-14 11:27 UTC, penmaher commented
Sorry for the delay in responding. 

If I said to include Line numbers then that is a terrible suggestion - I can't remember making it and can't easily see it now. I think I might have only been referring to line numbers to provide context for what I was saying. 

Only a few minor things to change:
1. I think the definition of Ts is not as obvious as it could be. Suggest replacing "(SST, Ts)" with "(SST) noted as $T_s$ below." I know it is more wordy but I think it is clearer.
2. I mented above but will say here too in case it is not seen. The formula for T_s in "APE aquaplanet (analytic form)" has not rendered correctly.

I think once those two small things are done we are ready to pass to Stephen for review.

2021-01-15 18:00 UTC, matthewjhenry commented
Thank you for the corrections @penmaher !  :)
I did the suggested edits along with a few more minor corrections.

Over to you @sit23 for the review, and then to @RuthG for quality control.

2021-01-18 08:37 UTC, penmaher approved these changes

2021-01-18 08:37 UTC, penmaher commented
Approval from me for this. @sit23  over to you.

2021-01-18 14:10 UTC, sit23 commented
OK - I realistically won't get to this for a week or two. Sorry about that. Will do it as soon as I can.

2021-02-24 14:27 UTC, penmaher commented
I am going to make some additions to this page, after the group discussion, to give some more context to the q-flux part. Once that is done I will commit the changes to this PR and then pass over to @sit23

2021-02-24 15:29 UTC, penmaher commented
@matthewjhenry can you check out my suggested changes and pass onto @sit23 if you are happy with them.

@sit23, in your review, can you critique the new section on q-fluxes, specifically step 2. When I have created q-fluxes in the past I have not used your script which is references in the doc. Could you check this makes sense and it suitable please?

2021-02-24 15:34 UTC, matthewjhenry commented
Checked your last commit @penmaher, looks a lot clearer, I have nothing to add. Thanks for fixing all the lower-case q's! :)

Over to you, @sit23.

2021-05-19 16:53 UTC, RuthG commented
Looks great, thanks Matthew!  
I'm open to disagreement, but I have some suggestions to restructure things to hopefully make it a little clearer. 
I've tried to suggest copy-paste-able text inserts to make this easier because personally I really appreciate these from coauthors etc., but no obligation to actually copy-paste them if you think they're nonsense!

l8-15: It might be clearer to reframe this introduction to overview the broad mixed layer options in the module, rather than trying to outline the namelist parameters. e.g.
```
The SST options are:
    - prescribe SST from an input file (``do_sc_sst`` namelist option)
    - prescribe SST to follow an AquaPlanet Experiment protocol (APE) analytic form (``do_ape_sst`` namelist option)
    - calculate SST based on the surface fluxes and mixed layer depth of a **slab ocean**, with the option of including a Q-flux (either analytic or read from a file)

Each of these options are discussed below, followed by an outline of the implicit time-stepping process used when SST is not prescribed. Note that only the final case will generate a closed surface energy budget.
```

I'd then suggest reordering the subsections to match the list i.e.:
- Input SST file
- APE aquaplanet (analytic SST)
- Slab ocean
- Implicit timestepping procedure


l22:  mixed_layer_init and  idealized_moist_phys would be good in `` ``s

l27: Perhaps basic but for novice users you could briefly explain what a slab ocean is here e.g.
```
To allow the SST to evolve based on the surface fluxes, the atmosphere can be coupled to a slab ocean, whose depth is specified by the namelist parameter ``depth``. This also allows a closed surface energy budget, useful for e.g. simulations with increased greenhouse gases.

In this case, during the initialisation....
```

I'd also suggest folding the Q-flux outline (and perhaps the implicit timestepping as well actually) into this section, and then it's very clear it's only relevant to 'coupled' slab ocean runs. 


l76: This is true where the Q-flux aims to mimic an input SST field. Some users may also want to use an idealised Q-flux with a different form to those included in the model. So maybe this bit could be generalised a little e.g.

```
Isca is able to calculate an analytic Q-flux, appropriate to an aquaplanet, following Merlis et al 2013 [MerlisEtAl2013] if ``do_qflux`` is True. Additionally, an analytic warmpool can be added  by setting ``do_warmpool``.  The warmpool structure is set in ``Isca/src/atmos_param/qflux/qflux.f90``. Alternatively an arbitrary Q-flux may be read from a file if ``load_qflux`` is True. 

In the case where both a specific SST distribution (e.g. AMIP climatology) and closed surface energy budget are desired, a Q-flux input file can be generated by running a control experiment with the prescribed SST, creating a NetCDF Q-flux file offline and then passing this file to the model via the python interface run script.

1. Run....
```

Otherwise looks good to me! The hardcoded land and albedo options look intrinsically confusing

2022-03-24 14:53 UTC, merged